version: '2'
services:
  api:
    build: ./api
    depends_on:
      - db_test
      - db_development
      - db_production
    environment:
      - POSTGRES_DEVELOPEMENT_URL=postgres://postgres:testtest@db_development:5432/hikari?sslmode=disable
      - POSTGRES_PRODUCTION_URL=postgres://postgres:testtest@db_production:5432/hikari?sslmode=disable
      - POSTGRES_TEST_URL=postgres://postgres:testtest@db_test:5432/hikari?sslmode=disable
      - DATABASE_POOL_SIZE=25
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - "./api/server:/usr/src/server"
      - "./api/Gruntfile.js:/usr/src/Gruntfile.js"
      - "api_node_modules:/usr/src/node_modules"
    ports:
      - "3000:3000"
    links:
      - "db_test"
      - "db_development"
      - "db_production"
    command: grunt

  db_test:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=testtest
    volumes:
      - "db_test_volume:/var/lib/postgresql/data"
      - "./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./database/schema:/src/schema"
    ports:
      - 5400:5432

  db_development:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=testtest
    volumes:
      - "db_development_volume:/var/lib/postgresql/data"
      - "./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./database/schema:/src/schema"
    ports:
      - 5401:5432

  db_production:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=testtest
    volumes:
      - "db_production_volume:/var/lib/postgresql/data"
      - "./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./database/schema:/src/schema"
    ports:
      - 5402:5432

  proxy:
    image: nginx
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/nginx.conf"
      - "./proxy/certificates/:/etc/nginx/ssl"
    links:
      - "api"

volumes:
  db_test_volume:
  db_development_volume:
  db_production_volume:
  api_node_modules:
